#ifndef MY_IOCTL_H
#define MY_IOCTL_H

#define IOC_MY_TYPE 'z'	// same as DRVO_MAGIC

#define IOC_NR_OPENREADCNT 5
#define IOC_NR_OPENWRITECNT 6
#define IOC_NR_CLEAR 7
#define IOC_NR_SET_BUFFER 8


// INT FOR MINOR DEVICE NUMBER
#define IOC_OPENREADCNT _IO(IOC_MY_TYPE, IOC_NR_OPENREADCNT)


