#ifndef MY_IOCTL_H
#define MY_IOCTL_H

#define IOC_MY_MAGIC 0xA4			

#define IOC_NR_OPENREADCNT 5
#define IOC_NR_OPENWRITE 6
#define IOC_NR_CLEAR 7
#define IOC_NR_SET_IGNORE_MODE 8


// INT FOR MINOR DEVICE NUMBER
#define IOC_OPENREADCNT _IO(IOC_MY_TYPE, IOC_NR_OPENREADCNT)
#define IOC_OPENWRITE _IO(IOC_MY_TYPE, IOC_NR_OPENWRITE)
#define IOC_CLEAR _IO(IOC_MY_TYPE, IOC_NR_CLEAR)

#endif
